# Generated by Django 4.1.7 on 2023-02-20 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=100)),
                ('about_description', models.TextField()),
                ('interest_description', models.TextField()),
                ('date_atu', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 13, 24, 254110))),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_description', models.CharField(max_length=200)),
                ('date_atu', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 13, 24, 256853))),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.user')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('experience_description', models.TextField()),
                ('date_atu', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 13, 24, 255060))),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resume.user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('date_atu', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 13, 24, 256007))),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resume.user')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_name', models.CharField(max_length=200)),
                ('awards_description', models.CharField(max_length=200)),
                ('date_atu', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 13, 24, 257749))),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='resume.user')),
            ],
        ),
    ]
