# Generated by Django 4.1.7 on 2023-02-20 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_atu',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 30, 52, 134605)),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_atu',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 30, 52, 132307)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_atu',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 30, 52, 131016)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='date_atu',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 30, 52, 133459)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_atu',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 23, 30, 52, 129760)),
        ),
    ]
